parameters:
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 10.0
      val: 0.0
    Va:
      active: false
      angle: 0.0
      lb: -20.5
      ub: 20.5
      val: 0.0
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp2:
      active: false
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp3:
      active: false
      lb: 0.01
      ub: 3.75
      val: 1.0
    lam:
      active: false
      lb: 523.0
      ub: 528.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    type:
      general: null
    ud:
      active: false
      angle: 0.0
      lb: -100.0
      ub: 100.0
      val: 0.0
  species1:
    Te:
      active: false
      lb: 0.01
      ub: 1.5
      val: 0.6
    fe:
      active: false
      dim: 1
      fe_decrease_strict: false
      lb: -100.0
      length: 3999
      m_asym: 1.0
      m_theta: 0.0
      symmetric: false
      temp_asym: 1.0
      type:
        DLM: null
      ub: -0.5
      v_res: 0.1
      val: []
    m:
      active: true
      lb: 2.0
      matte: false
      ub: 5.0
      val: 3.0
    ne:
      active: false
      lb: 0.001
      ub: 1.0
      val: 0.2
    type:
      electron: null
  species2:
    A:
      active: false
      val: 40.0
    Ti:
      active: false
      lb: 0.001
      ub: 1.0
      val: 0.12
    Z:
      active: false
      lb: 0.5
      ub: 7.0
      val: 14.0
    fract:
      active: false
      val: 0.1
    type:
      ion: null

other:
    crop_window: 1
    BinWidth: 10
    NumBinInRng: 0
    TotalNumBin: 1023
    expandedions: False
    extraoptions:
        load_ion_spec: False
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
    PhysParams:
        background: [0, 0]
        norm: 0
    iawoff: 0
    iawfilter: [1, 4, 24, 528]
    CCDsize: [1024, 1024]
    flatbg: 0
    gain: 1
    points_per_pixel: 1
    ang_res_unit: 10
    lam_res_unit: 5
    refit: True
    refit_thresh: 0.25
    calc_sigmas: False

plotting:
    n_sigmas: 3
    rolling_std_width: 5
    data_cbar_u: 1.1
    data_cbar_l: 0
    ion_window_start: 525
    ion_window_end: 528
    ele_window_start: 425
    ele_window_end: 625
    

data:
    launch_data_visualizer: false
    shotnum: 101675
    shotDay: False
    fit_rng:
        blue_min: 450
        blue_max: 510
        red_min: 545
        red_max: 650
        iaw_min: 350
        iaw_max: 352
        iaw_cf_min: 526.4
        iaw_cf_max: 526.6
        forward_epw_start: 400
        forward_epw_end: 700
        forward_iaw_start: 524
        forward_iaw_end: 528
    bgscaleE: 1.0
    bgscaleI: 0.1
    bgshotmult: 1
    ele_lam_shift: 0.0
    ion_loss_scale: 1.0
    ele_t0: 0
    ion_t0_shift: 0
    probe_beam: P9
    dpixel: 2
    lineouts:
        type:
            pixel
        start: 500
        end: 502
        skip: 1
    background:
        type:
            pixel
        slice: 900


    
optimizer:
    # use adam for nn / stochastic gradient descent
    # use L-BFGS-B for full batch / parameter learning
    # although adam will work here too
    method: adam
    hessian: False
    y_norm: True
    x_norm: False
    grad_method: AD
    grad_scalar: 1.0
    batch_size: 6
    num_epochs: 1
    learning_rate: 0.0001
    parameter_norm: True
    refine_factor: 1
    num_mins: 1

nn:
    use: false
    conv_filters: 32|16|16 #|32|32
    linear_widths: 32|16

dist_fit:
    window:
        len: 0.2 #should be even
        type: hamming # one of [hamming, hann, bartlett]

mlflow:
    experiment: inverse-thomson-scattering
    run: base