data:
    shotnum: 94475
    lineouts:
        type:
            range
        start: 90
        end: 950
        skip: 20
    background:
        type:
            Fit
        slice: 94477

other:
    extraoptions:
        load_ion_spec: False
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
        spectype: angular
    PhysParams:
        widIRF:
            spect_stddev_ion: 0.015
            spect_stddev_ele: 0.1
            spect_FWHM_ele: 0.9
            ang_FWHM_ele: 1.0
    refit: False
    refit_thresh: 5.0
    calc_sigmas: False

mlflow:
    experiment: inverse-thomson-scattering
    run: angular_2D_forward_test
    
machine: gpu

parameters:
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 10.0
      val: 0.0
    Va:
      active: false
      angle: 0.0
      lb: -40.5
      ub: 40.5
      val: 0.0
    amp1:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp2:
      active: true
      lb: 0.01
      ub: 3.75
      val: 1.0
    amp3:
      active: false
      lb: 0.01
      ub: 3.75
      val: 1.0
    lam:
      active: true
      lb: 523.0
      ub: 528.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    type:
      active: false
      general: null
    ud:
      active: false
      angle: 0.0
      lb: -10.0
      ub: 30.0
      val: 5.0
  species1:
    Te:
      active: true
      lb: 0.01
      ub: 2.0
      val: 1.0
    fe:
      active: false
      dim: 1
      fe_decrease_strict: false
      lb: -100.0
      length: 256
      m_asym: 1.0
      m_theta: 0.0
      symmetric: false
      temp_asym: 2.0
      type:
        DLM: null
      ub: -0.5
      v_res: 0.05
      val: []
    m:
      active: false
      intens: 4.55
      lb: 2.0
      matte: false
      ub: 5.0
      val: 3.5
    ne:
      active: true
      lb: 0.03
      ub: 2.0
      val: 0.4
    type:
      active: false
      electron: null
  species2:
    A:
      active: false
      val: 1.0
    Ti:
      active: false
      lb: 0.01
      same: false
      ub: 1.0
      val: 0.03
    Z:
      active: false
      lb: 0.5
      ub: 1.0
      val: 1.0
    fract:
      active: false
      val: 1.0
    type:
      active: false
      ion: null