parameters:
    amp1:
        val: 1.0
        active: True
        lb: 0.01
        ub: 3.75
    amp2:
        val: 1.0
        active: True
        lb: 0.01
        ub: 3.75
    amp3:
        val: 1.
        active: False
        lb: 0.01
        ub: 3.75
    lam:
        val: 524.5
        active: True
        lb: 523.0
        ub: 528.0
    Te:
        val: 1.0
        active: True
        lb: 0.01
        ub: 1.5
    Te_gradient:
        val: 0.0
        active: False
        lb: 0.
        ub: 10.
        num_grad_points: 1
    Ti:
        val: 0.2
        active: False
        lb: 0.01
        ub: 3.0
    Z:
        val: 8.
        active: False
        lb: 1.0
        ub: 25.0
    A:
        val: 14.
        active: False

    ud:
        val: 0.0
        active: False
        lb: -2.0
        ub: 2.0
    Va:
        val: 0.0
        active: False
        lb: -1.1
        ub: 2.5
    ne:
        val: 0.4
        active: True
        lb: .001
        ub: 1.0
    ne_gradient:
        val: 0.
        active: False
        lb: 0.
        ub: 15.
        num_grad_points: 1
    m:
        val: 3.5
        active: False
        lb: 2.0
        ub: 5.0
    fe:
        val: []
        active: True
        length: 256
        type:
            DLM:
        lb: -100.
        ub: -0.5
        fe_decrease_strict: True
        symmetric: False
        dim: 1
        v_res: 0.1
        temp_asym: 2.0

data:
    shotnum: 94475
    lineouts:
        type:
            range
        start: 90
        end: 950
        skip: 20
    background:
        type:
            Fit
        slice: 94477

other:
    extraoptions:
        load_ion_spec: False
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
    refit: False
    refit_thresh: 5.0

mlflow:
    experiment: inverse-thomson-scattering-d2
    run: archis-test