data:
  background:
    slice: 900
    type: pixel
  bgscaleE: 1.0
  bgscaleI: 0.1
  bgshotmult: 1
  dpixel: 3
  ele_lam_shift: 0.0
  ele_t0: 0
  fit_rng:
    blue_max: 510
    blue_min: 450
    iaw_cf_max: 526.5
    iaw_cf_min: 526.5
    iaw_max: 526.8
    iaw_min: 526.2
    red_max: 650
    red_min: 545
  ion_loss_scale: 1.0
  ion_t0_shift: 0.0
  launch_data_visualizer: true
  lineouts:
    end: 510
    skip: 1
    start: 500
    type: pixel
  probe_beam: P9
  shotDay: false
  shotnum: 101675
dist_fit:
  window:
    len: 0.2
    type: hamming
mlflow:
  experiment: inverse-thomson-scattering
  run: base
nn:
  conv_filters: 32|32|16
  linear_widths: 16|8
  use: false
optimizer:
  batch_size: 4
  grad_method: AD
  hessian: true
  learning_rate: 0.0001
  method: l-bfgs-b
  num_epochs: 10
  num_mins: 8
  parameter_norm: true
  refine_factor: 0
  sequential: true
  x_norm: false
  y_norm: true
other:
  BinWidth: 10
  CCDsize:
  - 1024
  - 1024
  NumBinInRng: 0
  PhysParams:
    background:
    - 0
    - 0
    norm: 0
  TotalNumBin: 1023
  ang_res_unit: 10
  calc_sigmas: false
  crop_window: 256
  ele_window_end: 625
  ele_window_start: 425
  expandedions: false
  extraoptions:
    fit_EPWb: true
    fit_EPWr: true
    fit_IAW: false
    load_ele_spec: true
    load_ion_spec: false
  flatbg: 0
  gain: 1
  iawfilter:
  - 1
  - 4
  - 24
  - 528
  iawoff: 0
  ion_window_end: 528
  ion_window_start: 525
  lam_res_unit: 5
  points_per_pixel: 5
  refit: false
  refit_thresh: 0.25
parameters:
  A:
    active: false
    val: 40
  Te:
    active: false
    gradient: 0.0
    lb: 0.01
    ub: 3.0
    val: 0.5
  Te_gradient:
    active: false
    lb: 0.0
    num_grad_points: 1
    ub: 10.0
    val: 0.0
  Ti:
    active: false
    lb: 0.01
    ub: 3.0
    val: 0.2
  Va:
    active: false
    val: 0
  Z:
    active: false
    lb: 1.0
    ub: 25.0
    val: 1.0
  amp1:
    active: false
    lb: 0.0
    ub: 10.0
    val: 1.0
  amp2:
    active: false
    lb: 0.0
    ub: 10.0
    val: 1.0
  amp3:
    active: false
    lb: 0.0
    ub: 10.0
    val: 1.0
  blur:
    active: false
    lb: 0.0
    ub: 10.0
    val: []
  fe:
    active: false
    fe_decrease_strict: true
    lb: -100.0
    length: 3999
    symmetric: false
    type:
      DLM: null
    ub: -0.5
    val: []
  fitprops:
    active: false
    val: []
  fract:
    active: false
    val: 1
  lam:
    active: false
    lb: 523.0
    ub: 528.0
    val: 526.5
  m:
    active: false
    lb: 2.0
    ub: 5.0
    val: 2.0
  ne:
    active: false
    gradient: 0.0
    lb: 0.001
    ub: 10.0
    val: 0.2
  ne_gradient:
    active: false
    lb: 0.0
    num_grad_points: 1
    ub: 15.0
    val: 0.0
  specCurvature:
    active: false
    lb: 0.1
    ub: 10.0
    val: []
  ud:
    active: false
    val: 0
plotting:
  data_cbar_l: 0
  data_cbar_u: data
  n_sigmas: 3
  rolling_std_width: 5
