series:
  param1: Z
  vals1: [[9.,1.], [10.5,1.], [11.5,1.],[12.2,1.],[13.,1.],[14.4,1.],[15.2,1.]]
  param2: Te
  vals2: [0.2137, 0.3893, 0.4788, 0.5357, 0.5915, 0.6696, 0.6739]
  param3: Ti
  vals3: [0.02137, 0.03893, 0.04788, 0.05357, 0.05915, 0.06696, 0.06739]
  param4: ne
  vals4: [0.1387, 0.18, 0.2067, 0.2189, 0.2293, 0.2311, 0.2311]
parameters:
    amp1:
        val: 1.
        active: True
        lb: 0.01
        ub: 3.75
    amp2:
        val: 1.
        active: True
        lb: 0.01
        ub: 3.75
    amp3:
        val: 1.0
        active: True
        lb: 0.01
        ub: 3.75
    lam:
        val: 526.5
        active: True
        lb: 523.0
        ub: 528.0
    Te:
        val: .400
        active: True
        lb: 0.01
        ub: 1.5
    Te_gradient:
        val: 0.0
        active: False
        lb: 0.
        ub: 10.
        num_grad_points: 1
    Ti:
        val: 0.040
        active: True
        lb: 0.001
        ub: 1.0
    Z:
        val: [6., 1.]
        active: True
        lb: 0.5
        ub: 7.0
    A:
        val: [40., 1.]
        active: False
    fract:
        val: [.40, .60]
        active: False
    ud:
        val: 0.0
        active: True
        lb: -100.0
        ub: 100.0
    Va:
        val: 0.0
        active: False
        lb: -20.5
        ub: 20.5
    ne:
        val: 0.23
        active: True
        lb: 0.001
        ub: 1.0
    ne_gradient:
        val: 0.
        active: False
        lb: 0.
        ub: 15.
        num_grad_points: 1
    m:
        val: 3
        active: False
        lb: 2.0
        ub: 5.0
    fe:
        val: []
        active: False
        length: 3999
        type:
            DLM:
        lb: -100.
        ub: -0.5
        fe_decrease_strict: False
        symmetric: False
        dim: 1

data:
    shotnum: 101675
    lineouts:
        type:
            pixel
        start: 340
        end: 660
        skip: 4
    background:
        type:
            Fit
        slice: 900
        show: False

other:
    extraoptions:
        load_ion_spec: True
        load_ele_spec: True
        fit_IAW: False
        fit_EPWb: True
        fit_EPWr: True
        spectype: temporal
    PhysParams:
        widIRF:
            spect_stddev_ion: 0.015
            spect_stddev_ele: 0.1
    refit: False
    refit_thresh: 5.0
    calc_sigmas: False


mlflow:
    experiment: inverse-thomson-scattering
    run: Ar-H-40-60-time_series_20per_hotter
    
machine: gpu